[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jlpyhttp"
version = "1.0.1"
dependencies = [
    "JLPyUtil @ git+https://github.com/JamesLikier/jlpyutil",
]